### ISSUE TITLE
Experiment: quote marks around blockquotes

### ISSUE THREAD

**Issue by waldyrious** [waldyrious/downstyle#36]
The left bar is becoming somewhat of a standard, and inconspicuous enough, but quote marks (if they could be added in a similarly unobtrusive way) could be more intuitive.

Maybe even try to emulate an effect like [this](https://www.infoq.com/news/2017/05/github-electron-desktop-client) (in a subtler way, though), using CSS only.

**Comment by waldyrious** [comment]
Here are the results of an experiment I made:
```css
blockquote{ position: relative; background: #f6f6f6; }
blockquote::before { content: '“'; font-family: 'Linux Libertine'; position: absolute; left:  -0.5em; color: #ddd; font-size: 5em; line-height:1em; }
blockquote::after  { content: '”'; font-family: 'Linux Libertine'; position: absolute; right: -0.5em; color: #ddd; font-size: 5em; line-height:1em; }
```

Before:
![screenshot from 2018-01-19 18-53-50](https://user-images.githubusercontent.com/478237/35166825-16a50878-fd4b-11e7-81c8-40f154e83bfd.png)

After:
![screenshot from 2018-01-19 18-53-09](https://user-images.githubusercontent.com/478237/35166828-196a0c16-fd4b-11e7-8198-faa208f45c95.png)

Looks nice enough (probably would need more top and bottom margin in the shaded version), but the code is way too complex to justify what is just a "nice-to-have", really. I'll close for now unless I can come up with a clever way to implement this with shorter code.

**Comment by waldyrious** [comment]
For future reference, there are a bunch of neat (but even more complex!) styles here: https://1stwebdesigner.com/css-snippets-blockquotes/

**Comment by waldyrious** [comment]
Hmm, perhaps there's a compact enough one here: https://css-tricks.com/snippets/css/simple-and-nice-blockquote-styling/

```css
blockquote:before { color: #ddd; content: open-quote; font-size: 4em; line-height: .1em; vertical-align: -.4em; margin-right: .1em; }
blockquote:after { color: #ddd; content: close-quote; font-size: 4em; line-height: .1em; vertical-align: -.4em; margin-left: .1em; }
```

Or the DRYer variant:

```css
blockquote:before, blockquote:after { color: #ddd; font-size: 4em; line-height: .1em; vertical-align: -.4em; }
blockquote:before { content: open-quote; margin-right: .1em; }
blockquote:after { content: close-quote; margin-left: .1em; }
```

But is the niceness worth adding a whole 3 lines?... I'm more inclined to say no.
